---
- name: "install node exporter."
  unarchive:
    src: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/eksctl
    dest: /usr/local/bin/
    remote_src: yes
    mode: "0777"

- name: create cluster
  shell: |
    eksctl create cluster \
    --name capstone-cluster \
    --region us-east-1 \
    --fargate
