---
- name: "install node exporter."
  unarchive:
    src: https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/eksctl
    dest: /usr/local/bin/
    remote_src: yes
    mode: "0777"

- name: install python
  shell: |
    python3 get-pip.py

- name: install aws
  shell: |
    pip3 install --upgrade pip \
    && pip3 install \
        awscli \
    && rm -rf /var/cache/apk/*

- name: create cluster
  shell: |
    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile user2 && aws configure set --profile user2 && aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile user2 && aws configure set region "$AWS_DEFAULT_REGION" --profile user2 && aws configure set output "text" --profile user2
    eksctl create cluster \
    --name capstone-cluster \
    --region us-east-1 \
    --fargate
