#01-ECR-Nginx-Deployment.yml
apiVersion: v1
kind: Deployment
metadata:
  name: kubeapp-ecr-deploy
  labels:
    name: kubeapp-ecr-deploy
    app: kubeapp-ecr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubeapp-ecr-pod
      app: kubeapp-ecr
  template:
    metadata:
      name: kubeapp-ecr-pod
      labels:
        name: kubeapp-ecr-pod
        app: kubeapp-ecr
    spec:
      containers:
        - name: kubeapp-ecr-container
          image: carlosolivares9/capstoneproject:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
