#02-ECR-Nginx-NodePortService.yml
apiVersion: v1
kind: Service
metadata:
  name: kubeapp-ecr-nodeport-service
  labels:
    app: kubeapp-ecr
spec:
  type: NodePort
  selector:
    app: kubeapp-ecr
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30072
