version: 2.1
orbs:
  slack: circleci/slack@4.5.3

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environments ${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation delete-stack --stack-name capstone-ecr-${CIRCLE_WORKFLOW_ID:0:7}
            aws cloudformation delete-stack --stack-name capstone-network-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  deploy-ecr-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy ecr
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/ecr.yml \
              --tags project=capstone \
              --stack-name "capstone-ecr-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --region=us-east-1

  upload-docker:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --no-cache \
            python3 \
            py3-pip \
            && pip3 install --upgrade pip \
            && pip3 install \
                awscli \
            && rm -rf /var/cache/apk/*
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker
          command: |
            cd backend
            docker build -t capstoneproject .
            docker images
      - run:
          name: Tag docker image
          command: |
            cd backend
            export ECRURI=$(aws cloudformation list-exports --query "Exports[?Name=='${CIRCLE_WORKFLOW_ID:0:7}-ECR-Uri'].Value" --no-paginate --output text)
            export registry=${$(aws cloudformation list-exports --query "Exports[?Name=='${CIRCLE_WORKFLOW_ID:0:7}-ECR-Uri'].Value" --no-paginate --output text)%:*}
            echo "$registry"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${registry}
            export test=$(aws ecr get-login)
            echo "$ECRURI"
            echo ${ECRURI}:latest
            docker tag capstoneproject ${ECRURI}:latest
            docker images
            docker push ${ECRURI}:latest
            exit 1

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: install tar and gzip
          command: |
            yum install -y tar gzip
      - run:
          name: Deploy network
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --tags project=capstone \
              --stack-name "capstone-network-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides EnvironmentName="${CIRCLE_WORKFLOW_ID:0:7}" \
              --region=us-east-1
            exit 1
      - destroy-environment

workflows:
  default:
    jobs:
      - deploy-ecr-infrastructure:
          filters:
            branches:
              only: main
      - upload-docker:
          filters:
            branches:
              only: main
          requires: [deploy-ecr-infrastructure]
