version: 2.1
orbs:
  slack: circleci/slack@4.5.3

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environments ${CIRCLE_WORKFLOW_ID:0:7}"
            aws cloudformation delete-stack --stack-name capstone-network-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: install tar and gzip
          command: |
            yum install -y tar gzip
      - run:
          name: Deploy network
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --tags project=udapeople \
              --stack-name "capstone-network-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides EnvironmentName="${CIRCLE_WORKFLOW_ID:0:7}" \
              --region=us-east-1
            exit 1
      - destroy-environment

workflows:
  default:
    jobs:
      - deploy-infrastructure:
          filters:
            branches:
              only: main
